version: '3.9'

services:
  db:
    image: postgres:13
    container_name: clinica_p2_db
    environment:
      POSTGRES_DB: pediatra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 202010039
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: clinica_p2_web
    command: >
      sh -c "python manage.py migrate &&
             gunicorn ProyectoFinal.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - static_volume:/app/static  # Para archivos estáticos
      - media_volume:/app/media    # Para archivos de medios
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=ProyectoFinal.settings
    links:
      - db

  nginx:
    image: nginx:latest
    container_name: clinica_p2_nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf       # Configuración del servidor nginx
      - static_volume:/app/static                # Cambiado a volúmenes consistentes
      - media_volume:/app/media                  # Cambiado a volúmenes consistentes

volumes:
  postgres_data:
  static_volume:
  media_volume:
