# Generated by Django 5.1.1 on 2024-09-22 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuarios_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='active_account',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='fisrt_name',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='first_name',
            field=models.CharField(default='Desconocido', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cui',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
