# Generated by Django 5.1.1 on 2024-09-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuarios_birth_date_usuarios_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='login_attempts',
            field=models.BigIntegerField(default=0),
        ),
    ]
