# Generated by Django 5.1.1 on 2024-10-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_remove_bebeconsulta_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profesores/'),
        ),
    ]
