# Generated by Django 5.1.1 on 2024-10-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_profesor_especialidad_profesor_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
