# Generated by Django 5.1.1 on 2024-10-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_profesor_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
