# Generated by Django 5.1.1 on 2024-09-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_usuarios_active_account_and_more'),
    ]

    operations = [
    ]
