# Generated by Django 5.1.1 on 2024-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_usuarios_cui'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
