# Generated by Django 5.1.1 on 2024-09-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuarios_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
