# Generated by Django 5.1.1 on 2024-09-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20240922_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cui',
            field=models.BigIntegerField(),
        ),
    ]
