# Generated by Django 5.1.1 on 2024-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_profesor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BebeConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('consulta', models.TextField()),
            ],
        ),
    ]
