# Generated by Django 5.1.1 on 2024-10-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_bebeconsulta_datos_adicionales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebeconsulta',
            name='consulta',
        ),
        migrations.AlterField(
            model_name='bebeconsulta',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bebeconsulta',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bebeconsulta',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bebeconsulta',
            name='tipo_sangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
