# Generated by Django 5.1.1 on 2024-10-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_articulos_catedratico_articulos_horario_inscripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='inscripcion',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='catedratico',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='horario',
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
