# Generated by Django 5.1.1 on 2024-10-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_remove_articulos_page_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='imagen_certificado',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para el certificado.', null=True, upload_to='certificados/'),
        ),
    ]
