# Generated by Django 5.1.1 on 2024-10-13 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_remove_reserva_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventario.articulos'),
            preserve_default=False,
        ),
    ]
