# Generated by Django 5.1.1 on 2024-10-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_reserva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_reservas/'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='notas_profesor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
