# Generated by Django 5.1.1 on 2024-09-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cui',
            field=models.BigIntegerField(),
        ),
    ]
