# Generated by Django 5.1.1 on 2024-09-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_alter_usuarios_cui'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
