# Generated by Django 5.1.1 on 2024-10-05 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_nota_inscripcion_remove_articulos_catedratico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='catedratico',
            field=models.ForeignKey(default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='horario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
