# Generated by Django 5.1.1 on 2024-10-06 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_articulos_estudiantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='page_url',
        ),
        migrations.AlterField(
            model_name='articulos',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
