# Generated by Django 5.1.1 on 2024-10-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_estudiante_alter_articulos_catedratico_curso_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='page_url',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articulos',
            name='welcome_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
