# Generated by Django 5.1.1 on 2024-10-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_articulos_imagen_certificado'),
        ('usuarios', '0019_remove_bebeconsulta_consulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bebe', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('datos_adicionales', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulos')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesor')),
            ],
        ),
    ]
