# Generated by Django 5.1.1 on 2024-10-13 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_reserva'),
        ('usuarios', '0021_profesor_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/bebes/'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='datos_adicionales',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='producto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.profesor'),
        ),
    ]
