# Generated by Django 5.1.1 on 2024-10-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_reserva_bebe_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
